version: 2.1

orbs:
  docker: circleci/docker@2.8.2  # Utilisation de la version 2.8.2 de l'orbe Docker

workflows:
  build-docker-image:
    jobs:
      - docker/publish:
          docker-password: $DOCKER_PASS  # Variable pour le mot de passe Docker Hub
          docker-username: $DOCKER_USER  # Variable pour le nom d'utilisateur Docker Hub
          image: "$DOCKER_USER/node-js-sample"  # Image Docker à builder
          tag: "latest"  # Tag de l'image (ici "latest", ou tu peux utiliser un tag dynamique comme $CIRCLE_BUILD_NUM)
