version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/app
    steps:
      - checkout  # Cette étape va cloner ton dépôt

      # Construire l'image Docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USER/node-js-sample .

      # Pousser l'image Docker vers Docker Hub (ou un autre registre)
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $DOCKER_USER/node-js-sample your_dockerhub_username/node-js-sample:latest
            docker push $DOCKER_USER/node-js-sample:latest

workflows:
  version: 2
  build:
    jobs:
      - build
