version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout  # Cette étape va cloner ton dépôt

      # Étape pour configurer Docker (si nécessaire)
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      # Construire l'image Docker
      - run:
          name: Build Docker image
          command: |
            docker build -t auredm/node-js-sample .

      # Pousser l'image Docker vers Docker Hub (ou un autre registre)
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag auredm/node-js-sample your_dockerhub_username/node-js-sample:latest
            docker push auredm/node-js-sample:latest

workflows:
  version: 2
  build:
    jobs:
      - build
