version: 2.1

orbs:
  docker: circleci/docker@2.4.0  # Utilisation de l'orbe officiel Docker

jobs:
  build-and-push:
    executor: docker/docker  # Utilisation d'un exécuteur Docker standard
    steps:
      - checkout  # Clone le dépôt

      - setup_remote_docker  # Active Docker (sans préciser de version)

      - docker/publish:
          image: "$DOCKER_USER/node-js-sample"
          tag: "latest"
          registry: "docker.io"
          login: true

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
